CREATE SCHEMA IF NOT EXISTS `ESCOLINHA` DEFAULT CHARACTER SET utf8 ;

USE `ESCOLINHA` ;

CREATE TABLE IF NOT EXISTS `ESC_RESPONSAVEIS` (
  `RES_CPF` VARCHAR(11) NOT NULL,
  `RES_NOME` VARCHAR(45) NOT NULL,
  `RES_ENDERECO` VARCHAR(60) NOT NULL,
  `RES_TELEFONE` VARCHAR(20) NOT NULL,
  `RES_EMAIL` VARCHAR(25) NULL,
  PRIMARY KEY (`RES_CPF`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ESC_ALUNOS` (
  `ALN_MATRICULA` INT NOT NULL AUTO_INCREMENT,
  `ALN_NOME` VARCHAR(45) NOT NULL,
  `ESC_RESPONSAVEIS_RES_CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ALN_MATRICULA`),
  INDEX `fk_ESC_ALUNOS_ESC_RESPONSAVEIS_idx` (`ESC_RESPONSAVEIS_RES_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_ESC_ALUNOS_ESC_RESPONSAVEIS`
    FOREIGN KEY (`ESC_RESPONSAVEIS_RES_CPF`)
    REFERENCES `ESC_RESPONSAVEIS` (`RES_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ESC_INSTRUTORES` (
  `INS_CPF` VARCHAR(11) NOT NULL,
  `INS_NOME` VARCHAR(45) NOT NULL,
  `INS_ENDERECO` VARCHAR(60) NOT NULL,
  `INS_TELEFONE` VARCHAR(20) NOT NULL,
  `INS_EMAIL` VARCHAR(25) NULL,
  PRIMARY KEY (`INS_CPF`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ESC_MODALIDADES` (
  `MOD_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `MOD_NOME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`MOD_CODIGO`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ESC_ESCOLINHAS` (
  `ELI_CODIGO` INT NOT NULL AUTO_INCREMENT,
  `ELI_HORARIO` VARCHAR(20) NOT NULL,
  `ELI_HORAS_SEMANA` INT NOT NULL,
  `ESC_INSTRUTORES_INS_CPF` VARCHAR(11) NOT NULL,
  `ESC_MODALIDADES_MOD_CODIGO` INT NOT NULL,
  PRIMARY KEY (`ELI_CODIGO`),
  INDEX `fk_ESC_ESCOLINHAS_ESC_INSTRUTORES1_idx` (`ESC_INSTRUTORES_INS_CPF` ASC) VISIBLE,
  INDEX `fk_ESC_ESCOLINHAS_ESC_MODALIDADES1_idx` (`ESC_MODALIDADES_MOD_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_ESC_ESCOLINHAS_ESC_INSTRUTORES1`
    FOREIGN KEY (`ESC_INSTRUTORES_INS_CPF`)
    REFERENCES `ESC_INSTRUTORES` (`INS_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESC_ESCOLINHAS_ESC_MODALIDADES1`
    FOREIGN KEY (`ESC_MODALIDADES_MOD_CODIGO`)
    REFERENCES `ESC_MODALIDADES` (`MOD_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ESC_ALUNOS_DAS_ESCOLINHAS` (
  `ALE_ALN_MATRICULA` INT NOT NULL,
  `ALE_ELI_CODIGO` INT NOT NULL,
  `ALE_DATA_MATRICULA` DATETIME NOT NULL,
  PRIMARY KEY (`ALE_ALN_MATRICULA`, `ALE_ELI_CODIGO`),
  INDEX `fk_ESC_ALUNOS_has_ESC_ESCOLINHAS_ESC_ESCOLINHAS1_idx` (`ALE_ELI_CODIGO` ASC) VISIBLE,
  INDEX `fk_ESC_ALUNOS_has_ESC_ESCOLINHAS_ESC_ALUNOS1_idx` (`ALE_ALN_MATRICULA` ASC) VISIBLE,
  CONSTRAINT `fk_ESC_ALUNOS_has_ESC_ESCOLINHAS_ESC_ALUNOS1`
    FOREIGN KEY (`ALE_ALN_MATRICULA`)
    REFERENCES `ESC_ALUNOS` (`ALN_MATRICULA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESC_ALUNOS_has_ESC_ESCOLINHAS_ESC_ESCOLINHAS1`
    FOREIGN KEY (`ALE_ELI_CODIGO`)
    REFERENCES `ESC_ESCOLINHAS` (`ELI_CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
